# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 802ca807163b00cd2eb0b23aa7437627b822cf6645016a36036668d9bf83cc504cf09d1d02104b4715035b5b2c1e34fa1593b60f51ff1b4315211bdb9de408da

test:
  secret_key_base: 0125c39549bfcc89fe1ff56dcaef04d1d7c1b5ae0f7159cf0cf3c8c57b3ee8fe9b792eed58e35db7b5ea058757ff5ab120c1182f4846a7d417327248256310c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
